[package]
name = "bullets"
version = "0.1.0"
description = "Minimal RSS TUI"
authors = ["Steve <contact@stevedylan.dev>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
ureq = "3"
crossterm = "0.29.0"
feedparser-rs = "0.5.3"
open = "5"
chrono = "0.4"
ratatui = "0.30.0"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
